camera:
  fx: 718.8560
  fy: 718.8560
  cx: 607.1928
  cy: 185.2157

odometry:
  detector: ORB # Possible values: ORB, SIFT, AKAZE, BRISK, FAST, BLOB, SURF <- (for use SURF pip install opencv-contrib-python and you have to manually compile OpenCV with contrib-modules and OPENCV_ENABLE_NONFREE CMake flag turned on.)
  descriptor: ORB # Possible values: ORB, SIFT, AKAZE, BRISK, SURF
  matcher: BFMatcher # Possible values: BFMatcher, FLANN
  opticalFlow: None # Possible values: None, Farneback, PyrLK
  methodForComputingE: RANSAC # Possible values: RANSAC, LMEDS

data:
  liveCamera: None # Possible values: None, specify port
  video: None # Possible values: None, specify path
  images: ../data_set/images # Possible values: None, specify path
  groundTruth: None # Possible values: None, specify path
  groundTruthTemplate: None # Possible values: KITTI, None, Default

settings:
  logs: True # Possible values: None, True
  seeTracking: True # Possible values: None, True
