camera:
  fx: 718.856
  fy: 718.856
  cx: 607.1928
  cy: 185.2157
odometry:
  detector: SIFT
  descriptor: AKAZE
  matcher: FLANN
  opticalFlow: LK
  methodForComputingE: RANSAC
data:
  liveCamera: None
  video: None
  images: ../data_set/images/set1
  groundTruth: ../data_set/gt_poses/00.txt
  groundTruthTemplate: KITTI
settings:
  logs: false
  seeTracking: None
